### ISSUE TITLE
Marine setup

### ISSUE THREAD

**Issue by domienbakker** [Sjoerd02/Faytech_Remote_M5stack#1]
Hi Sjoerd,

I found your repo via an article on faytech.nl.
It mentioned that you use your setup on a boat, can you please share some details about your setup?
Maybe share a couple of pictures. I am interested in buying a Faytech as well and use that with OpenCPN on my sailboat.
Many thanks.

Kind regards, 

Domien

**Comment by Sjoerd02** [comment]
Hallo Domien,


Below some pictures 

I am using it in conjunction with laptop mostly (wingps) , however have a monitor switch so I can easily  switch to openplotter

I am now using first half of season and it’s working well
Sometimes I unplug USB when in wet conditions doing a lot of trim. Also caused by the location
I am satisfied with touch operation. route planning I do on the laptop using a mouse.

When you’re based in NL or BE your welcome to come and have a look

KR Sjoerd






Verstuurd vanaf mijn iPhone

**Comment by domienbakker** [comment]
Hallo Sjoerd,

Leuk dat je een reactie stuurt,  plaatjes zie ik niet in je mail of op Github.
Wellicht dat je deze via mail kunt versturen?
Waar lig je ergens met je boot?
Zelf lig ik in Brouwershaven met m’n kleine Defender 27.
Zit ook een beetje aan het prutsen met OpenCPN, alleen de monitor is echt het probleem.
Ik moet investeren in een monitor die ik kan gebruiken in het buitenlicht, kwam daardoor bij Faytech uit.

With kind regards / Met vriendelijke groet,

Domien Bakker

***@***.***D77827.C77C78C0]
COAS Software Systems BV | Rottenburgseweg 25 | 3241 XD Middelharnis | Nederland
Tel: +31 (0) 187 - 49 75 23  | Mob: +31 (0) 6 12 73 68 70
E-mail: ***@***.******@***.***> | Website: www.coas.com<http://www.coas.com/>

**Comment by domienbakker** [comment]
Got my response.
